Feature: As a business owner, I want to be able to replace placeholder image with selected upload image during business profile creation (HAIR-66)
Brridge-Group/Lions-Gate-Hairr pull request #32
Opened 2022-05-17 01:32 UTC by CodeMeKathy

## Description
This Pull Request (PR) allows business owners to replace the placeholder image with a selected image to upload during business profile creation within the `<AddBusiness />` page.

## Acceptance Criteria
- [x] As a business owner, I want to be able to replace the placeholder image with a selected image to upload during business profile creation.

### Related Issue/Ticket

Closes #66

## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|     | :bug: Bug fix              |
| ✓   | :sparkles: New feature     |
| ✓   | :hammer: Refactoring       |
|     | :100: Add tests            |
|    | :link: Update dependencies |
|     | :scroll: Docs              |

## `<AddBusiness />` Page Images

<details>

<summary>Updated Add Business Page</summary>

![Screen Shot 2022-05-16 at 20 53 24](https://user-images.githubusercontent.com/32943879/168706442-bacc3468-6b5e-47b0-be75-acd02f9f8318.png)

![Screen Shot 2022-05-16 at 20 54 18](https://user-images.githubusercontent.com/32943879/168706407-3642b987-04b4-4372-b697-74d454ec3c19.png)

</details>

2022-05-19 20:04 UTC, cynthiaeddy approved these changes

2022-05-21 00:56 UTC, sergiobtos commented
@CodeMeKathy  you still need to fix : 
 - MyBusinessList.tsx => Button update Profile and add a bussiness : Their links are wrong. Look at the code here 
<div className='Profile_links'>
        <Link to={'#'}>
          <h6 className='btn--btn-primary'>update profile</h6>
        </Link>
        <Link to={'#'}>
          <h6 className='btn--btn-primary twoLines'>
            add a<br /> business
          </h6>
        </Link>

2022-05-21 01:00 UTC, sergiobtos requested changes
MyBusinessList.tsx => Button update Profile and add a bussiness : Their links are wrong. Look at the code here

<div className='Profile_links'>
        <Link to={'#'}>
          <h6 className='btn--btn-primary'>update profile</h6>
        </Link>
        <Link to={'#'}>
          <h6 className='btn--btn-primary twoLines'>
            add a<br /> business
          </h6>
        </Link>

2022-05-21 02:40 UTC, sergiobtos approved these changes
Good

2022-05-21 03:12 UTC, merged